---
- name: Setup Desktop Environment
  hosts: local
  become: true
  gather_facts: true

  vars_prompt:
    - name: git_user_name
      prompt: "ğŸ‘¤ Enter your Git user name"
      private: no

    - name: git_user_email
      prompt: "ğŸ“§ Enter your Git email address"
      private: no

    - name: github_token
      prompt: "ğŸ” Enter your GitHub Personal Access Token"
      private: yes

  roles:
    - tools
    - ansible_install
    - packer
    - terraform
    - git_setup
    - github_setup
